spring:
  application:
    name: gateway-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://admin:Password1@localhost:8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:Password1@localhost:8761/eureka

server:
  port: 8762